-- The previous migration (20261007164508_add_recipe_diet_type) was
-- generated by `prisma migrate dev` diffing against schema.prisma, which
-- has no knowledge of the pg_trgm GIN indexes added by hand in
-- 20261007140400_component_constraints (Prisma's schema language can't
-- express a GIN/trigram index). Prisma treated those indexes as drift and
-- silently dropped them. Restoring them here, and noting this interaction
-- in the README so it isn't repeated: any future `prisma migrate dev` run
-- will make the same mistake unless this migration (or an equivalent) is
-- re-applied after it, or these indexes are excluded from Prisma's diff by
-- some other means.

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS idx_recipes_name_trgm ON recipes USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_ingredients_name_trgm ON ingredients USING gin (name gin_trgm_ops);
